global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Application metrics
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['spring-app:8080']
    scrape_timeout: 10s

  # Spring Boot Actuator endpoints for additional metrics
  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['spring-app:8080']
    scrape_timeout: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(api_requests_total|api_response_time|business_operations_total|business_processing_time|order_value|active_users).*'
        target_label: metric_type
        replacement: 'custom'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
