# For Default profile
info:
  app:
    name: Spring Boot Monitoring with Grafana
    description: Demo application showcasing actuator endpoints and custom metrics
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Docker profile specific configuration
---
spring:
  config:
    activate:
      on-profile: docker

# Update server configuration for Docker
server:
  port: 8080
  address: 0.0.0.0

# Update management endpoints for Docker network
management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

info:
  app:
    name: Spring Boot Monitoring with Grafana
    description: Demo application showcasing actuator endpoints and custom metrics
    version: 1.0.0
